string(RANDOM LENGTH 8 ALPHABET "0123456789ABCDEF" PAYLOAD_SIGNATURE)
set(PAYLOAD_SIGNATURE "0x${PAYLOAD_SIGNATURE}")

set(IS_DEBUGGER_PRESENT_ID "0x0")
set(REMOTE_DEBUGGER_PRESENT_ID "0x1")
set(NTQUERY_ID "0x2")
set(EBS_ID "0x3")
set(RTL_QUERY_HEAP_ID "0x4")
set(MANUAL_CHECK_HEAP_PROTECTION "0x5")
set(CHECK_KUSER_SHARED_USER "0x6")

set(SUSPICIOUS_SIGNATURE_DETECTED "0x1000")
set(RECOVER_REQUEST "0x1001")

string(RANDOM LENGTH 16 ALPHABET "0123456789ABCDEF" KEY_EXCHANGE_SIGNATURE)
set(KEY_EXCHANGE_SIGNATURE "0x${KEY_EXCHANGE_SIGNATURE}")

set(PSK "{")
foreach (i RANGE 1 32)
    string(RANDOM LENGTH 2 ALPHABET "0123456789ABCDEF" PSK_TERM)
    set(PSK "${PSK} 0x${PSK_TERM},")
endforeach ()
set(PSK "${PSK} }")

string(RANDOM LENGTH 8 ALPHABET "0123456789ABCDEF" STOP_MAGIC_BYTE)
set(STOP_MAGIC_BYTE "0x${STOP_MAGIC_BYTE}")
